import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react"; // Import SessionProvider
import { Inter } from "next/font/google";
import { createOptimizedIndexes } from "@/lib/createIndexes";
import "./globals.css";
createOptimizedIndexes();
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Assume `session` is added to the props passed to RootLayout
export default function RootLayout({
  children,
  session, // Add session to the component's props
}: Readonly<{
  children: React.ReactNode;
  session?: any; // Type accordingly based on your session object's structure
}>) {
  return (
    <html lang="en" className=" light dark:dark text-foreground bg-background ">
      <SessionProvider session={session}>{/* Wrap children with SessionProvider */}
        <body className={`${inter.className} bg-gradient-to-t from-[#cfd9df] to-[#e2ebf0] dark:bg-dark-background dark:bg-blend-multiply`}>
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}